# Conclusion {-#conclusion}

In this dissertation, I proposed a framework to unify existing theories to understand polite language as reflecting a tradeoff between different goals that speakers may consider. 
Critically, language does not only reflect speakers' informational concerns to convey accurate information informatively, 
but also non-informational social concerns, such as following social norms and maintaining listeners' and speakers' own positive self-image (*face*).
In Chapter 1, I summarized previous approaches to polite language and argued that a goal-based framework can integrate different components that are important to explaining how polite speech emerges and is understood. 
Then I explained how existing empirical data with adults and children that can be explained through this goal-based framework.

In Chapters that followed, I presented evidence from our own empirical studies that demostrated children and adults' understanding of polite speech as reflecting a tradeoff between informational and social goals. 
Chapter 2 examined 2- to 4-year-old children's understanding of social goals behind language use, through the case study of polite requests with simple politeness markers such as "please," and "can you~". By 3 years, children were able to judge that speakers making polite requests were being more polite, and by 4 years children were able to reason that those speakers were also likely to be better play partners and to gain compliance to their requests. 

Chapter 3 examined older children's and adults' understanding of the tradeoff between social goals and informational goals, using the case study of white lies (versus blunt truths). By 6 years, children seem capable of using context information to reason about speaker goals and make judgments about whether the speaker was being nice or mean, and evaluate liars more positively given potential face threat to the listener than given no apparent face threat. 
We saw a developmental trend, where older children, like adults, rated polite liars more positively whereas younger participants tended to be divided. 
This age difference may be due to a discrepancy in goal priorities: Younger children may prioritize truth-telling, which can be a simple rule to follow (e.g., "Don't lie, always tell the truth") but as they get older, they might learn to consider other people's feelings and address the informational-social tradeoff more.

Finally, Chapter 4 examined adults' understanding of polite language in more detail, by looking at utterance prediction in a situation of potential face threat (e.g., speakers being asked to give feedback and answer "How was my poem?"), 
and proposed a model to formalize the notions of speaker goals as utilities that the speaker wants to maximize. 
We showed that our model predictions captured important key patterns of human judgments,
and that the model fit was superior to its variants with a subset of the three utilities of our model. 
Overall, the empirical work suggest that the goal-tradeoff framework both explains children's and adults' understanding of polite language well, and is useful for formalization and thus for making precise predictions of polite speech. 

What can we learn about the development of language understanding from this dissertation work?
Children start to show sensitivity to social goals behind language use from early on and are able to use that notion to judge polite versus impolite utterances accordingly by 3 years; 
by 6 years we see children being able to reason about the tradeoff between informational and social goals depending on the context,
finally, adults reason about polite utterances as reflecting a tradeoff between informational and social goals, that pertain to both saving the listener’s face but also being self-presentational, and that these notions can be represented by a formal model.

Naturally, this work could imply that language understanding evolves this way, such that
children first think about informational and social goals as largely separate rules that people need to follow, like “always tell the truth” or “say please when you make a request.” 
Then as they get older, children might start to think these two goals more integratively, as they get exposed to more situations where there is a clear tradeoff between the two. 
Finally, as they get even older, adults may start to pay attention to subtly different social concerns like saving the listener’s face versus presenting oneself as a good person, and address them differently.

But the current studies actually have not ruled out the possibility that young children in fact have some idea of the full tradeoff of all three goals. 
@asaba2018 has shown that 3- to 5-year-old children care about presenting their own competence to another person, and forgo opportunities to teach them new knowledge to take actions to show that they are competent.
Given that children act with self-presentational goals, it is plausible to think that children might use the notion of presentational goals to interpret other people’s utterances. 

The goal tradeoff framework thus provides us with a set of possible hypotheses that we can test about development of polite language understanding, and examine whether children start from the point of low competence to eventually get to high, adult-like competence, or children actually have adult-like competence to start with but perhaps with some performance obstacles that might conceal their capabilities.

In terms of what goals speakers might consider, 
this dissertation presented a framework that argues for a set of three different communicative goals that people might think about,
but it does not intend to argue that the list of goals is exhaustive; 
in fact, there could be many other utilities not explored here that people consider in language production. 
For example, the speaker might have a goal to try to achieve some immediate rewarding outcome in the world that surpasses informational or social goals. In another work, we have looked at some of these tradeoffs not in language understanding but in an active learning context, where people’s actions reflect tradeoffs between informational goals versus presentational goals versus immediate action goals, where people’s desire to look competent or get something to immediately work (like a machine to light up) could override their desire to gain new information [@yoon2018balancing]. The goal tradeoff framework can be a basis for exploring other goals that people might consider in different contexts.

What other factors might affect speakers’ goals for polite language production? 
In the current work, we considered how goal priorities might be shifted based on situational context (e.g., whether the listner baked or did not bake the cookies that are being asked about), but there are many other important factors that can contribute to the goal tradeoff decisions.
For example, people can shift their goal priorities based on who the listener is, where people might care more about informational goal when speaking to their close friend but they might care more about social face-saving when talking to a person who is older or has more authority than them. 
Indeed, @yoon2018balancing showed that adults predict an agent will make different decisions depending on whether their boss is present when they are about to choose an action to perform. 

Another important factor that has not been addressed is cultural, regional and linguistic variations. 
While we examined adults and children from the US only, these goal tradeoff decisions can interact differently depending on the speaker’s cultural norms, since other cultures might have different expectations for what goals are appropriate in a given situation. 
Indeed, preliminary work extending on Part 2 has shown some evidence that compared to US and Korean adults and older children who tend to say a polite liar is nice, Indian adults and children tend to say more often that the polite liar is *not* nice, which may be evidence that different cultures have different goal priorities depending on  context. 
It will be useful to think about how these variations across cultures and their interactions with different contexts and speaker and listener relationships might play a role in speaker decisions based on the goal tradeoff framework. 

Overall, this dissertation arguing for the framework of looking at polite language as reflecting goal tradeoffs helps further our understanding of how children and adults comprehend polite language, and how it can vary across contexts and cultures.
And politeness is just one way that language deviates from purely informational concern, as people try to boast, comfort, flirt, insult, and speak in many other ways that reflect our goals to affect others’ feelings or present particular views of ourselves. 
Thus, this framework will help advance our understanding of language comprehension and social cognition more broadly. 




---FIXME below---

There are limitations to the current theoretical framework and empirical evidence presented in here, that have important implications for future work. 
First, for the developmental work, Chapters 2 and 3 looked at distinct age groups, 2- to 4-year-olds and 5- to 8-year-olds respectively, making it difficult to tell how the polite speech understanding, especially regarding the tradeoff between informational and social goal, might develop across the entire relevant age span. 
For example, do 2- to 4-year-olds show even more of preference for prioritizing informational goals over social goals? Or do they not yet have the notion of goal tradeoff at all?
There were practical concerns that prevented younger children's participation in the study reported in Chapter 3, namely that it would be too difficult for younger children to understand the stories presented in that study (due to memory demand, tracking of second-order beliefs, etc.). 
It will be useful to conduct a follow-up task that is more accessible for younger children and can test their understanding of goal tradeoffs.
It will also be helpful to consider how children's utterance choices and evaluations may be formalized, which will help hone explanation for the development of polite language understanding and make precise predictions.

Second, the scope of contexts of polite speech use we explored thus far is limited. We have not examined other factors that may be integral to polite speech production and understanding, such as speaker-listener status differences (e.g., conversations between a teacher and student, instead of between friends), listener needs (e.g., listener is looking for feedback to enter a competition), and available utterances (e.g., other kinds of indirect speech such as "I don't think this cookie is very tasty").
Thus, it is an open question whether and how children and adults process these other kinds of relevant information and integrate them into their understanding of polite utterances. 

Also, here we addressed broadly three differentiable goals -- informational, prosocial, and self-presentational -- that speakers may consider, but in real life, there may be other goals that are important, or these goals may also be broken down further. 
For example, in the current work we supposed that speakers consider self-presentational goals to appear informative or to appear kind, but depending on the context, speakers may care about appearing competent and knowledgeable.
Indeed, people do account for this kind of presentational goal to determine their action in a social active learning context, where they must choose between maximal information gain (e.g., learn which button makes a machine work) versus presentation of oneself as competent [e.g., that they can make the machine work for sure; @yoon2018balancing].
Thus, future work should investigate how different desires than ones examined here may play roles in speakers' utterance choices.

Finally, the empirical studies presented here recruited participants in the US only, but there may be great variations in polite speech understanding depending on cultural norms and expectations. 
For example, some cultures and languages may emphasize prosocial goals more than informational goals and thus have expectations for speakers to prioritize kindness over informativity, whereas other cultures might value truthfulness as a greater virtue than face-saving.
Indeed, we have some preliminary evidence that Indian speakers, both adults and children, value informational goals more and are more charitable toward blunt truth-tellers than polite liars compared to US and Korean speakers. 
Formalisation and empirical test of these cultural variations will help further the understanding of polite language.

In sum, I argued for a goal-based framework for polite language understanding, in which speakers consider tradeoffs between informational and social concerns. 
Our empirical research shows that adults and children are sensitive to not only informational goals but also social goals behind language use, and consider tradeoffs between these goals when reasoning about speakers' utterance choices.
I also presented a formal model of the goal tradeoffs, which allowed for precise quantitative predictions that matched human adults' polite speech predictions well.
This theoretical approach accompanied by computational framework then can be a powerful tool in addressing possible future work to extend on many other factors that must be considered to explain human understanding of polite language, and pragmatics and social behaviors in general.






